### ISSUE TITLE
Problem: chain-maind crashed when input certain parameters for query

### ISSUE THREAD

**Issue by brianatcrypto** [crypto-org-chain/chain-main#360]
**Describe the bug**
chain-maind crashed when input certain parameters

**To Reproduce**
<to be provided by reporter>

**Expected behavior**
<to be provided by reporter>

**Screenshots**
<to be provided by reporter>

**Desktop (please complete the following information):**
 - chain-maind version
<to be provided by reporter>

**Additional context**
<to be provided by reporter>

**Comment by ilhamm24** [comment]
Step to produce: I running spam tx for the task then i stop it and trying to unjail my validator, then start spam tx again and got this message. I should restart my node to solve it
![image](https://user-images.githubusercontent.com/24799581/105660546-d0568500-5efd-11eb-816d-5868c8e44a39.png)
![image](https://user-images.githubusercontent.com/24799581/105660576-e6644580-5efd-11eb-8a3b-e4d6e6f598d2.png)

**Comment by ilhamm24** [comment]
if I'm not mistaken, I used to use crossfire's main node for sending tx

**Comment by brianatcrypto** [comment]
@ilhamm24 - I saw your email content as below:
How to produce:
1. I did spam txs with normal command but with while looping
2. I waiting for 2-5 minutes and i see the sequence didnt increase, but the txs command didnt show the errors

Could you please 
1. provide the scripts/commands you executed
2. what is the actual result?
3. what is the expected result?

What version of chain-maind?

**Comment by ilhamm24** [comment]
1. `while true; do sequenceNow=$((./chain-maind q account cro19x9tx5yt4k4ld0xq656knhtmejncdj7j5wasd0 -o json |  jq .sequence -r));./chain-maind tx bank send OkeSip cro16zsrjp9skhpn377z3765r9xndgx56t97wjj3me 1basetcro --chain-id crossfire --fees 5000basetcro --keyring-backend=test --sequence $((sequenceNow)) -y;done;` I forgot to use broadcast sync or async mode, but I guess it is sync
2. The result is wrong sequence, which it's right, because i got it from the query request and same with the lcd of crossfire main node
3. Should my transaction is broadcasted because the sequence is right

for the sequence number expect and actual is in my screenshoot

**Comment by tomtau** [comment]
this looks like a duplicate issue to https://github.com/crypto-org-chain/chain-main/issues/330#issuecomment-786380454
 feel free to reopen this issue if it is not and it can be reproduced on 0.9.1 after the testnet upgrade
