### ISSUE TITLE
Problem: chain-maind 3.3.3 binary release checksums don't seem correct

### ISSUE THREAD

**Issue by zkaizhi** [crypto-org-chain/chain-main#800]
**Describe the bug**
The checksums using sha256 don't seem to be correct, causing the AWS 1-click deployment to fail. 

**To Reproduce**
1. Download any of the 3.3.3 binaries
2. Calculate the sha256sum of the binary tar.gz file
3. Result is not equal to the shasums calculated in the checksum.txt file

**Expected behavior**
Sha256sum should be the same as the value in the checksums.txt file

**Comment by tomtau** [comment]
is it he case for other versions as well?

**Comment by tomtau** [comment]
@zkaizhi is it for all binaries or only the Linux one? I looked back at the audit log: https://github.com/crypto-org-chain/chain-main/actions/runs/1533798577 -- I recall that I had to restart the GoReleaser flow, because it failed to upload (there was some GH network issue)... and my guess is that GoReleaser may not be deterministic, so it perhaps created and uploaded a few binaries + checksum in one run, then it uploaded the Linux binary in another run, but the checksum remained from the previous run

**Comment by tomtau** [comment]
it looks like it's all binaries

**Comment by tomtau** [comment]
the new checksum file and explanation were added: https://github.com/crypto-org-chain/chain-main/releases/tag/v3.3.3
